name: Screenshots check

on:
  pull_request:
    branches:
      - main

jobs:
  checkScreenshots:
    name: Screenshots check

    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Yarn install
        run: yarn install --network-timeout 1000000

      - name: Run stories-check
        id: storiesCheck
        continue-on-error: true
        run: yarn stories-check

      - name: Commit story changes
        id: csc
        if: steps.storiesCheck.outcome == 'failure'
        uses: EndBug/add-and-commit@v8
        with:
          add: '.stories-approved'
          message: '[skip ci] [stories-check] Automated story changes'
          new_branch: ${{ github.head_ref }}
          default_author: github_actions

      - name: Run cypress-check
        id: cypressCheck
        continue-on-error: true
        run: yarn cypress-check

      - name: Commit cypress changes
        id: ccc
        if: steps.cypressCheck.outcome == 'failure'
        uses: EndBug/add-and-commit@v8
        with:
          add: '.cypress-approved'
          message: '[skip ci] [cypress-check] Automated cypress changes'
          new_branch: ${{ github.head_ref }}
          default_author: github_actions